### ISSUE TITLE
Add a custom ResourceSpec BuildGCS to embed GCS resource in TaskRun

### ISSUE THREAD

**Issue by tejal29** [knative/build-pipeline#451] opened 2019-01-29 23:05 UTC
## Expected Behavior
In issue #440, we added ability to embed resource spec  in Task run.
Adding a new Type "BuildGCS" for  a GCS resource spec. 
This task is Part 2 of #313 

If we want people to be able to migrate from the Build and BuildTemplate types in knative/build to Task and TaskRun in pipelines, we need to support the same GCS functoinality that was provided by the GCS source type.

## Actual Behavior

Right now GCS can be embedded in TaskRun, however [the Build gcs functionality](https://github.com/knative/build/blob/1b37ef70a2529c5cc49b7eff012ffc5ae463cefb/pkg/reconciler/build/resources/pod.go#L103) is a bit different from the GCS type that was initially created for Pipelines:

* The GCS resource type initially added to pipelines just does a straight upload/download of binary data in a bucket
* The GCS source in Build uses [the gcs-fetcher image](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gcs-fetcher) which supports:
  * Archive formats (e.g. automatically zipping, unzipping)
  * [Manifests](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gcs-fetcher#source-manifests)

## Steps to Reproduce the Problem

Take an existing Build which uses the Build source type, such as [the gcs archive example](https://github.com/knative/build/tree/5d8bfc32e91c175f30046455687fd842a496842e/test/gcs-archive), and try to convert it to a Task + TaskRun using the types we already have .

## Additional Info

Related work in #313, [this doc by @shashwathi ](https://github.com/knative/build-pipeline/issues/313#issuecomment-453270121) outlines possible solutions to this problem.

**Comment by bobcatfish** [comment] 2019-02-12 22:16
I updated the description of this issue to reflect why we need to add this new type.

@tejal29 I think the only thing left to address here before we close the issue is to add docs to resources.md?

**Closed** 2019-02-15 23:46 UTC
